name: Publish .NET Class Library to NuGet

on:
  push:
    branches:
      - main  
jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x' 

    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v3.0.0
      with:
        versionSpec: '6.x'
      id: gitversion

    - name: Set version variables
      run: echo "##[set-output name=VERSION;]${{ steps.gitversion.outputs.semver }}"

    - name: Display version
      run: echo "Generated version:${{ steps.gitversion.outputs.semver }}"

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release --no-restore

    - name: Pack .NET Project
      run: dotnet pack src/OrchardCore.Media.Minio --configuration Release --no-build --output ./artifacts /p:PackageVersion=${{ steps.gitversion.outputs.semver }}

    - name: Publish to NuGet
      run: dotnet nuget push ./artifacts/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
